### ISSUE TITLE
Install compas-FoFin in Rhino ( Mac )

### ISSUE THREAD

**Issue by jf---** [BlockResearchGroup/compas-FoFin#59]
**Describe the bug**

Can't install the `FF__toolbar`

---

Following the [compas_fofin](https://blockresearchgroup.gitbook.io/compas-fofin/quick-start/getting-started) tutorial, I can't complete installation, specifically, see step 5, where I'm invoking:

```bash
python -m compas_fofin.rhino.install
```

from the terminal, and get the following output:

```
(compas) ➜  compas_fofin git:(master) ✗ python -m compas_fofin.rhino.install
Traceback (most recent call last):
  File "/Users/jelle/mambaforge/envs/compas/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/jelle/mambaforge/envs/compas/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/jelle/Code/CADCAM/compas_fofin/src/compas_fofin/rhino/__init__.py", line 25, in <module>
    from .cablenetartist import *
  File "/Users/jelle/Code/CADCAM/compas_fofin/src/compas_fofin/rhino/cablenetartist.py", line 18, in <module>
    from compas_rhino.artists import MeshArtist
  File "/Users/jelle/mambaforge/envs/compas/lib/python3.10/site-packages/compas_rhino/artists/__init__.py", line 138, in <module>
    from .robotmodelartist import RobotModelArtist
  File "/Users/jelle/mambaforge/envs/compas/lib/python3.10/site-packages/compas_rhino/artists/robotmodelartist.py", line 7, in <module>
    import Rhino.Geometry
ModuleNotFoundError: No module named 'Rhino'
```

So `CPython` `__init__.py` tries to load an `IronPython` module.
On the surface of it, it seems that rather the `ui` directory is to be installed.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/620988/207657695-eedc0a70-1e25-4eef-9bcc-b8d46dc7d57c.png">

**Comment by jf---** [comment]
Apologies, the above ( obviously, 26 Nov 2020 ) applied to a super ol' version, I just didn't notice the repo being out of date.
Possible I had an ancient repo with a "master" rather than "main" branch checkedout.

--

Threw away the ol' repo, checkout a fresh out, run 

```
python -m compas_fofin.rhino.install
```

>>> This installation procedure is deprecated.
>>> Use `python -m compas_rhino.install` instead.

```
python -m compas_rhino.install
```

And all is good in the world
