### ISSUE TITLE
Unable to run modify node attribute command

### ISSUE THREAD

**Issue by nellienator** [BlockResearchGroup/compas-FoFin#60]
**Describe the bug**
When running cablemesh_modify_nodes command. 
This error comes up 
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Roaming\McNeel\Rhinoceros\7.0\scripts\compas_ui\rhino\forms\error.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\danie\AppData\Roaming\McNeel\Rhinoceros\7.0\Plug-ins\PythonPlugins\FoFin{18a65b9c-1a08-43ef-a1fd-ef458f0a1fa0}\dev\FF_cablemesh_modify_nodes_cmd.py", line 23, in RunCommand
    cablemesh.settings["show.vertices:anchors"] = True
  File "C:\Users\danie\AppData\Roaming\McNeel\Rhinoceros\7.0\scripts\compas_ui\values\settings.py", line 15, in __setitem__
    self.value[key].value = value
KeyError: show.vertices:anchors

Trying the Cartenary Cables tutorial.  

**Screenshots**

![ezgif com-optimize](https://github.com/BlockResearchGroup/compas-FoFin/assets/132958946/02654e9b-e7f2-457d-921d-903dac244427)

**Comment by tomvanmele** [comment]
hi,

we released a new version of COMPAS FormFinder. please check out the basic instructions [here](https://github.com/BlockResearchGroup/compas-FoFin), and the docs [here](https://blockresearchgroup.gitbook.io/compas-fofin), and let us know if you still have problems...

best,
tom
